//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosia.PL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AmbrosiaEntities : DbContext
    {
        public AmbrosiaEntities()
            : base("name=AmbrosiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFoodItem> tblFoodItems { get; set; }
        public virtual DbSet<tblMeal> tblMeals { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWorkout> tblWorkouts { get; set; }
        public virtual DbSet<tblWorkoutType> tblWorkoutTypes { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> SPCalcCaloriesBurned(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<decimal> caloriesPerMinute)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var caloriesPerMinuteParameter = caloriesPerMinute.HasValue ?
                new ObjectParameter("CaloriesPerMinute", caloriesPerMinute) :
                new ObjectParameter("CaloriesPerMinute", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SPCalcCaloriesBurned", startTimeParameter, endTimeParameter, caloriesPerMinuteParameter);
        }
    }
}
