//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosia.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkout
    {
        public System.Guid Id { get; set; }
        public System.Guid WorkoutTypeId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblWorkoutType tblWorkoutType { get; set; }
    }
}
